# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

pool:
  vmImage: ubuntu-22.04


steps:
- script: |
    sudo sed -i -- 's/^# *deb-src/deb-src/' /etc/apt/sources.list
    sudo apt-get build-dep gnuradio
    sudo apt-get install gnuradio gnuradio-dev gr-osmosdr librtlsdr-dev libuhd-dev libhackrf-dev libitpp-dev libpcap-dev liborc-dev cmake git swig build-essential pkg-config doxygen python3-numpy python3-waitress python3-requests gnuplot-x11
    # Tell op25 to use python3
    echo "/usr/bin/python3" > op25/gr-op25_repeater/apps/op25_python
  displayName: 'install depedencies'      
- script: |
    mkdir build
    cd build
    cmake ../
    make
  displayName: 'make'
